---
title: "newvars"
author: "Samanalie Perera, 300486075"
date: "2022-09-04"
output: html_document
---

```{r}
library(RNHANES)
library(foreign)
```

#loading other varaibles 
#demographic, occupation, sleep disorders, alcohol use, recreational drug use, smoking.

## Demographics Data
```{r}
DEMdata2005 <- nhanes_load_data("DEMO_D", "2005-2006")
DEMdata2007 <- nhanes_load_data("DEMO_E", "2007-2008")
DEMdata2009 <- nhanes_load_data("DEMO_F", "2009-2010")
DEMdata2011 <- nhanes_load_data("DEMO_G", "2011-2012")
DEMdata2013 <- nhanes_load_data("DEMO_H", "2013-2014")

download.file("https://wwwn.cdc.gov/nchs/nhanes/2015-2016/DEMO_I.xpt", 
              temp <- tempfile(), 
              mode="wb")

DEMdata2015 <- foreign::read.xport(temp)

################################################################################

download.file("https://wwwn.cdc.gov/nchs/nhanes/2017-2018/P_DEMO.xpt", 
              tf <- tempfile(), 
              mode="wb")

DEMdata2017 <- foreign::read.xport(tf)
```

```{r}
demo_col <- c('SEQN', 'RIDAGEYR', 'RIAGENDR', 'RIDRETH1', 'DMDMARTL', 'INDFMPIR')

reduce_DEMdata2005 <- DEMdata2005[,demo_col]
reduce_DEMdata2007 <- DEMdata2007[,demo_col]
reduce_DEMdata2009 <- DEMdata2009[,demo_col]
reduce_DEMdata2011 <- DEMdata2011[,demo_col]
reduce_DEMdata2013 <- DEMdata2013[,demo_col]
reduce_DEMdata2015 <- DEMdata2015[,demo_col]

demo2005_2015 <- do.call(rbind, list(reduce_DEMdata2005, reduce_DEMdata2007,
                            reduce_DEMdata2009, reduce_DEMdata2011,
                            reduce_DEMdata2013, reduce_DEMdata2015))

names(demo2005_2015) <- c('id', 'age','gender','race', 'marital_status', 'Family PIR')
```

```{r}
demo_col <- c('SEQN', 'RIDAGEYR', 'RIAGENDR', 'RIDRETH1', 'DMDMARTZ', 'INDFMPIR')
reduce_DEMdata2017 <- DEMdata2017[,demo_col]
names(reduce_DEMdata2017) <- c('id', 'age','gender','race', 'marital_status', 'Family PIR')

demo <- do.call(rbind, list(demo2005_2015, reduce_DEMdata2017))
demo <- demo[!(demo$marital_status == 77 | demo$marital_status == 99),]
demo <- na.omit(demo)
head(demo)
```

```{r}
summary(demo)
dim(demo)
```

## Sleep Disorders
```{r}
SLPdata2005 <- nhanes_load_data("SLQ_D", "2005-2006")
SLPdata2007 <- nhanes_load_data("SLQ_E", "2007-2008")
SLPdata2009 <- nhanes_load_data("SLQ_F", "2009-2010")
SLPdata2011 <- nhanes_load_data("SLQ_G", "2011-2012")
SLPdata2013 <- nhanes_load_data("SLQ_H", "2013-2014")

download.file("https://wwwn.cdc.gov/nchs/nhanes/2015-2016/SLQ_I.xpt", 
              temp <- tempfile(), 
              mode="wb")

SLPdata2015 <- foreign::read.xport(temp)

################################################################################

download.file("https://wwwn.cdc.gov/nchs/nhanes/2017-2018/P_SLQ.xpt", 
              tf <- tempfile(), 
              mode="wb")

SLPdata2017 <- foreign::read.xport(tf)
```

```{r}
sleep_col <- c('SEQN', 'SLD010H', 'SLQ050')

reduce_SLPdata2005 <- SLPdata2005[,sleep_col]
reduce_SLPdata2007 <- SLPdata2007[,sleep_col]
reduce_SLPdata2009 <- SLPdata2009[,sleep_col]
reduce_SLPdata2011 <- SLPdata2011[,sleep_col]
reduce_SLPdata2013 <- SLPdata2013[,sleep_col]

sleep2005_2013 <- do.call(rbind, list(reduce_SLPdata2005, reduce_SLPdata2007,
                             reduce_SLPdata2009, reduce_SLPdata2011,
                             reduce_SLPdata2013))

names(sleep2005_2013) <- c('id', 'sleep_hours', 'trouble_sleeping_history')

sleep2005_2013 <- sleep2005_2013[!(sleep2005_2013$sleep_hours == 77 | sleep2005_2013$sleep_hours == 99),]
```

```{r}
sleep_col <- c('SEQN', 'SLD012', 'SLQ050')
reduce_SLPdata2015 <- SLPdata2015[,sleep_col]
names(reduce_SLPdata2015) <- c('id', 'sleep_hours', 'trouble_sleeping_history')

reduce_SLPdata2017 <- SLPdata2017[,sleep_col]
names(reduce_SLPdata2017) <- c('id', 'sleep_hours', 'trouble_sleeping_history')


sleep <- do.call(rbind, list(sleep2005_2013, reduce_SLPdata2015,
                             reduce_SLPdata2017))

sleep <- na.omit(sleep)

head(sleep)
```

```{r}
summary(sleep)
dim(sleep)
```

## Alcohol Use
```{r}
ALCdata2005 <- nhanes_load_data("ALQ_D", "2005-2006")
ALCdata2007 <- nhanes_load_data("ALQ_E", "2007-2008")
ALCdata2009 <- nhanes_load_data("ALQ_F", "2009-2010")
ALCdata2011 <- nhanes_load_data("ALQ_G", "2011-2012")
ALCdata2013 <- nhanes_load_data("ALQ_H", "2013-2014")

download.file("https://wwwn.cdc.gov/nchs/nhanes/2015-2016/ALQ_I.xpt", 
              temp <- tempfile(), 
              mode="wb")

ALCdata2015 <- foreign::read.xport(temp)

################################################################################

download.file("https://wwwn.cdc.gov/nchs/nhanes/2017-2018/P_ALQ.xpt", 
              tf <- tempfile(), 
              mode="wb")

ALCdata2017 <- foreign::read.xport(tf)
```

```{r}
alcohol_col <- c('SEQN', 'ALQ130')

reduce_ALCdata2005 <- ALCdata2005[,alcohol_col]
reduce_ALCdata2007 <- ALCdata2007[,alcohol_col]
reduce_ALCdata2009 <- ALCdata2009[,alcohol_col]
reduce_ALCdata2011 <- ALCdata2011[,alcohol_col]
reduce_ALCdata2013 <- ALCdata2013[,alcohol_col]
reduce_ALCdata2015 <- ALCdata2015[,alcohol_col]
reduce_ALCdata2017 <- ALCdata2017[,alcohol_col]

alcohol <- do.call(rbind, list(reduce_ALCdata2005, reduce_ALCdata2007,
                             reduce_ALCdata2009, reduce_ALCdata2011,
                             reduce_ALCdata2013, reduce_ALCdata2015,
                             reduce_ALCdata2017))

names(alcohol) <- c('id', 'drinks_per_occasion')

alcohol <- alcohol[!(alcohol$drinks_per_occasion == 777 | alcohol$drinks_per_occasion == 999),]

alcohol <- na.omit(alcohol)

head(alcohol)
```

```{r}
summary(alcohol)
dim(alcohol)
```

## Smoking
```{r}
SMKdata2005 <- nhanes_load_data("SMQ_D", "2005-2006")
SMKdata2007 <- nhanes_load_data("SMQ_E", "2007-2008")
SMKdata2009 <- nhanes_load_data("SMQ_F", "2009-2010")
SMKdata2011 <- nhanes_load_data("SMQ_G", "2011-2012")
SMKdata2013 <- nhanes_load_data("SMQ_H", "2013-2014")

download.file("https://wwwn.cdc.gov/nchs/nhanes/2015-2016/SMQ_I.xpt", 
              temp <- tempfile(), 
              mode="wb")

SMKdata2015 <- foreign::read.xport(temp)

################################################################################

download.file("https://wwwn.cdc.gov/nchs/nhanes/2017-2018/P_SMQ.xpt", 
              tf <- tempfile(), 
              mode="wb")

SMKdata2017 <- foreign::read.xport(tf)
```

```{r}
smoking_col <- c('SEQN', 'SMQ020')

reduce_SMKdata2005 <- SMKdata2005[,smoking_col]
reduce_SMKdata2007 <- SMKdata2007[,smoking_col]
reduce_SMKdata2009 <- SMKdata2009[,smoking_col]
reduce_SMKdata2011 <- SMKdata2011[,smoking_col]
reduce_SMKdata2013 <- SMKdata2013[,smoking_col]
reduce_SMKdata2015 <- SMKdata2015[,smoking_col]
reduce_SMKdata2017 <- SMKdata2017[,smoking_col]

smoking <- do.call(rbind, list(reduce_SMKdata2005, reduce_SMKdata2007,
                             reduce_SMKdata2009, reduce_SMKdata2011,
                             reduce_SMKdata2013, reduce_SMKdata2015,
                             reduce_SMKdata2017))

names(smoking) <- c('id', 'smoked_at_least_100')

smoking <- smoking[!(smoking$smoked_at_least_100 == 7 | smoking$smoked_at_least_100 == 9),]

smoking <- na.omit(smoking)

head(smoking)
```

```{r}
summary(smoking)
dim(smoking)
```