# Demographic
## Columns
cols = c("SEQN", "RIAGENDR", "RIDAGEYR", "RIDRETH3", "DMDEDUC3 ", "DMDHHSIZ", "DMDFMSIZ", "DMDHHSZA", "DMDHHSZB", "DMDHHSZE", "INDHHIN2", "INDFMIN2")

## Missing Data Code 
DMDBORN4 > 2 or .
DMDEDUC3 > 15 or .
DMDEDUC2 > 5 or .
DMDMARTL > 6 or .
FIALANG = .
INDHHIN2 > 15 or .
INDFMIN2 > 15 or .

# Sleep Disorders
## Columns
cols = c("SEQN", "SLD012", "SLD013")

## Missing Data Code
SLD012 = .
SLD013 = .
SLQ030 > 3 or .
SLQ040 > 3
SLQ050 > 2
SLQ120 > 4

# Alcohol Use
## COlumns
cols = c("SEQN", ALQ111", "ALQ121", "ALQ130", "ALQ142", "ALQ280", "ALQ290", "ALQ151", "ALQ170")

## Missing Data Code
ALQ111 > 2
ALQ121 > 10
ALQ130 > 15
ALQ142 > 10
ALQ270 > 10
ALQ280 > 10
ALQ290 > 10
ALQ151 > 2
ALQ170 > 30

# Smoking
## Columns
cols = c("SEQN", "SMQ020", "SMD030", "SMQ040", "SMQ078", "SMD641", "SMD650", "SMQ621", "SMD630", "SMQ661", "SMQ670", "SMQ848", "SMQ890", "SMQ895", "SMQ900", "SMQ905", "SMQ910", "SMQ915")

## Missing Data Code
SMQ020 > 2
SMD030 > 777
SMQ040 > 3
SMQ078 > 7
SMD641 > 30
SMD650 > 95
SMQ621 > 8
SMD630 > 17
SMQ661 > 10
SMQ670 > 2
SMQ848 > 777
SMQ890 > 2
SMQ895 > 30
SMQ900 > 2
SMQ905 > 30
SMQ910 > 2
SMQ915 > 30


# Physical Activity
## Columns
ALL

## Missing Data Code
PAQ605 > 2
PAQ610 > 7
PAD615 > 840
PAQ620 > 2
PAQ625 > 7
PAD630 > 840
PAQ635 > 7
PAQ640 > 7
PAD645 > 660
PAQ650 > 2
PAQ655 > 7
PAD660 > 480
PAQ665 > 2
PAQ670 > 7
PAD675 > 540
PAD680 > 1320

# Physical Functioning
## Columns
cols = c("PFQ020", "PFQ030", "PFQ049", "PFQ051", "PFQ054", "PFQ057", "PFQ059", "PFQ090")

## Missing Data Code
PFQ020 > 2
PFQ030 > 2
PFQ049 > 2
PFQ051 > 2
PFQ054 > 2
PFQ057 > 2
PFQ059 > 2
PFQ090 > 2

# Weight History
## Columns
cols = c("SEQN", "WHD010", "WHD020", "WHQ030", "WHQ040", "WHD050", "WHQ070", "WHQ225", "WHD110", "WHD120", "WHD140", "WHQ150", "WHQ190'
)

## Missing Data Code
WHD010 > 82
WHD020 > 484
WHQ030 > 3
WHQ040 > 3
WHD050 > 520
WHQ070 > 2
WHQ225 > 5
WHD110 > 630
WHD120 > 530
WHD140 > 630
WHQ150 > 80
WHQ190 > 2

























